### ISSUE TITLE
Not able to build my project after introducing ngx-monaco-editor

### ISSUE THREAD

**Issue by syllogismos** [atularen/ngx-monaco-editor#15]
I'm able to make monaco editor work using `ng serve` even though it gives me an error message. It complies after subsequent file edits.

The build fails with the same error message.

Here is the output
```
ERROR in Metadata version mismatch for module /Code/application/node_modules/ngx-monaco-editor/editor.module.d.ts, found version 4, expected 3

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Code/application/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

I updated my angular cli from 1.0.3 to 1.6 and its not building there as well. But I get a slightly different error.

```
ERROR in Error: Metadata version mismatch for module /Code/debug/node_modules/ngx-monaco-editor/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /Code/debug/src/app/app.module.ts, resolving symbol AppModule in /Code/debug/src/app/app.module.ts
    at syntaxError (/Code/debug/node_modules/@angular/compiler/bundles/compiler.umd.js:1724:34)
    at simplifyInContext (/Code/debug/node_modules/@angular/compiler/bundles/compiler.umd.js:24854:23)
    at StaticReflector.simplify (/Code/debug/node_modules/@angular/compiler/bundles/compiler.umd.js:24866:13)
    at StaticReflector.annotations (/Code/debug/node_modules/@angular/compiler/bundles/compiler.umd.js:24314:41)
    at _getNgModuleMetadata (/Code/debug/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Code/debug/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/Code/debug/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Code/debug/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Code/debug/node_modules/@ngtools/webpack/src/plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Code/debug/node_modules/@ngtools/webpack/src/plugin.js:495:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

```

I looked at similar errors in other repos on google, and it seems like its because of differences in Angular 5 and Angular 4.. like for example this issue https://github.com/angular/material2/issues/8229

How do I fix this?
Thank you.

**Comment by syllogismos** [comment]
https://github.com/syllogismos/monacotest

Created a sample project that fails for me, can you tell me how to fix this

**Comment by atul-wizni** [comment]
@syllogismos  ngx-monaco-editor v1.0.0 and above supports Angular 5 only. The error you got was because you are using 'angular/compiler': "^4.0.0" which complains about a version mismatch in the metadata when using the Angular 5 compiled ngx-monaco-editor version 1.1.1.

You should use v1.1.1 after upgrading to Angular 5 or use v1.0.4 with angular 4

In sample to bind ngModel you have to import FormsModule in AppModule.

**Comment by syllogismos** [comment]
Thank you, downgrading to 1.0.4 worked for me.

**Comment by rajkumarm-iprogrammer** [comment]
sudo npm install ngx-monaco-editor@1.0.4 --save

By installing 1.0.4 it's working for me

Thank you :) @syllogismos
