### ISSUE TITLE
Unable to use build-optimizer

### ISSUE THREAD

**Issue by ItsEcholot** [atularen/ngx-monaco-editor#4]
I'm unable to use the --build-optimizer flag with Angular-CLI when using this library.
I have tracked this issue down to the [following line](https://github.com/atularen/ngx-monaco-editor/blob/master/src/platform/editor/editor.component.ts#L4) where we should import the Observable library with `rxjs/Observable` instead of the generic `rxjs/Rx`.

**Comment by atul-wizni** [comment]
I have verified build with --build-optimizer flag on @angular/cli@1.4.2 is working fine. Will you please provide me cli project for reproduction.

**Comment by ItsEcholot** [comment]
I sadly can't release the whole project but here's the logs:

```
ERROR in ./node_modules/rxjs/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42959:28)
    at checkExpression (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42898:42)
    at checkExpressionCached (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42779:38)
    at checkReturnStatement (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45418:54)
    at checkSourceElement (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46763:28)
    at Object.forEach (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:1506:30)
    at checkBlock (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:44563:16)
    at checkSourceElement (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41990:21)
    at checkDeferredNodes (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46828:25)
    at checkSourceFileWorker (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46863:17)
    at checkSourceFile (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46842:13)
    at Object.forEach (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:1506:30)
 @ ./node_modules/rxjs/observable/bindCallback.js 2:32-68
 @ ./node_modules/rxjs/add/observable/bindCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./node_modules/ngx-monaco-editor/editor.component.js
 @ ./src/$$_gendir/app/dashboard/websites/websites.component.ngfactory.ts
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/rxjs/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42959:28)
    at checkExpression (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42898:42)
    at checkExpressionCached (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:42779:38)
    at checkReturnStatement (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:45418:54)
    at checkSourceElement (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46763:28)
    at Object.forEach (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:1506:30)
    at checkBlock (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:44563:16)
    at checkSourceElement (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:41990:21)
    at checkDeferredNodes (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46828:25)
    at checkSourceFileWorker (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46863:17)
    at checkSourceFile (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:46842:13)
    at Object.forEach (C:\Users\Marc\Desktop\Projects\FrostBolt5\frontend\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:1506:30)
 @ ./node_modules/rxjs/observable/bindNodeCallback.js 2:36-76
 @ ./node_modules/rxjs/add/observable/bindNodeCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./node_modules/ngx-monaco-editor/editor.component.js
 @ ./src/$$_gendir/app/dashboard/websites/websites.component.ngfactory.ts
 @ ./src/$$_gendir/app/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

The following command was used to build, I tried the build process on two different computers but no difference `ng build --prod --aot --build-optimizer`

But as soon as I adjusted the mentioned line to `rxjs/Observable` it compiles correctly. I don't think there's a negative side effect to the import change and might even decrease the package size as only the really used module (Observable) is being imported instead of the complete Rx package.

**Comment by atul-wizni** [comment]
I have made required changes and published. Please check with version 1.0.4.

**Comment by ItsEcholot** [comment]
Works perfectly now, thanks for the quick fix
